# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: JupyterLab Contrib Team
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: jupyterlab-browser-storage
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab Drive to save files in the browser storage
python_name: jupyterlab_browser_storage
repository: https://github.com/jupyterlab-contrib/jupyterlab-browser-storage
test: true
viewer_name: ''

